#! /bin/sh

# Clean boundaries directory
cd boundaries
for bv in limitedTemperature fixedCurrentDensity fixedLocationCurrentDensity fixedLocationAlternatingCurrent
do
    cd $bv
    wclean
    cd ../
done
cd ../

# Clean thermo directory
cd thermo
for tv in compressibleFluidLut
do
    cd $tv
    wclean
    cd ../
done
cd ../

# Clean solver directory
cd solvers
for sv in plasmaArc
do
    cd $sv
    wclean
    cd ../
done
