#! /bin/sh

# Build boundaries directory
cd boundaries
for bv in limitedTemperature fixedCurrentDensity
do
    cd $bv
    wmake libso
    cd ../
done
cd ../

# Build solver directory
cd solvers
for sv in plasmaArc
do
    cd $sv
    wmake
    cd ../
done
